version: '3.8'

services:
  mongo:
    image: mongodb/mongodb-enterprise-server
    environment:
      MONGO_INITDB_ROOT_USERNAME: college
      MONGO_INITDB_ROOT_PASSWORD: BIM_LOCAL1
    volumes:
      - mongo_data:/data/db
    ports:
      - "27018:27017"

  redis:
    image: redis
    command: redis-server --requirepass BIM_LOCAL1
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"

  s3:
    image: scality/s3server:latest
    ports:
      - "8000:8000"

volumes:
  mongo_data:
  redis_data:
